package capabilities

// TableRowCount is the number of frozen first-GA capability table rows.
const TableRowCount = 25

// catalog is the frozen first-GA REST↔MCP table. Order is the
// implementation-design capability list; do not reorder or rename in place.
func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "NTP bound, snapshot installed, and management bound or explicitly off. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
		},
		{
			ID: VersionGet, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Version"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_version_get"}},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesGet, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_capabilities_get"}, Resources: []string{"labntp://capabilities"}},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: StatusGet, Title: "Agent status", Version: VersionTag,
			Description:    "Listeners, revisions, hostTime, and ready.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_status_get"}, Resources: []string{"labntp://status"}},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaGet, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_schema_get"}, Resources: []string{"labntp://schema/config"}},
			ServiceMethods: []string{"ConfigSchema"},
		},
		{
			ID: FeaturesList, Title: "Features", Version: VersionTag,
			Description:    "Frozen live vs reset-only catalog.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "FeatureList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/features"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_features_list"}, Resources: []string{"labntp://features"}},
			ServiceMethods: []string{"Features"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Redacted spec plus revision metadata.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_state_get"}, Resources: []string{"labntp://state"}},
			ServiceMethods: []string{"GetState"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document and/or operations without writing.",
			RequiredScopes: []string{ScopeNTPAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ValidateIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_state_validate"}},
			ServiceMethods: []string{"Validate"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical desired-state export plus drift material.",
			RequiredScopes: []string{ScopeNTPAdmin}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Export"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_state_export"}},
			ServiceMethods: []string{"Export"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, wipe the query log, and swap. Never writes the file.",
			RequiredScopes: []string{ScopeNTPAdmin}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ResetIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_state_reset"}},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: ChangesPlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeNTPAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_change_plan"}},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangesApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. expectedRevision is required.",
			RequiredScopes: []string{ScopeNTPAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_change_apply"}},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: SessionCreate, Title: "Create session", Version: VersionTag,
			Description: "Cookie + CSRF session for the operator UI. Accepts bearer.",
			Idempotent:  false, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "POST", Path: "/v1/session"}},
		},
		{
			ID: SessionGet, Title: "Get session", Version: VersionTag,
			Description: "Current session principal (cookie or bearer). Cookie path returns CSRF for reload recovery.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/session"}},
		},
		{
			ID: SessionDelete, Title: "Delete session", Version: VersionTag,
			Description: "Clear the operator UI session cookie.",
			Idempotent:  true, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "DELETE", Path: "/v1/session"}},
		},
		{
			ID: FiltersList, Title: "List filters", Version: VersionTag,
			Description:    "List first-match filters in document order.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "FilterList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/filters"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_filters_list"}, Resources: []string{"labntp://filters"}},
			ServiceMethods: []string{"ListFilters"},
		},
		{
			ID: FiltersGet, Title: "Get filter", Version: VersionTag,
			Description:    "Get one filter by name.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Filter"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/filters/{name}"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_filters_get"}},
			ServiceMethods: []string{"GetFilter"},
		},
		{
			ID: FiltersPut, Title: "Put filter", Version: VersionTag,
			Description:    "Upsert a filter by name. Goes through the same compile+swap as Apply.",
			RequiredScopes: []string{ScopeNTPWrite}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "PutFilterIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "PUT", Path: "/v1/filters/{name}"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_filters_put"}},
			ServiceMethods: []string{"PutFilter"},
		},
		{
			ID: FiltersDelete, Title: "Delete filter", Version: VersionTag,
			Description:    "Remove a filter by name. Catch-all remains required.",
			RequiredScopes: []string{ScopeNTPWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "DELETE", Path: "/v1/filters/{name}"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_filters_delete"}},
			ServiceMethods: []string{"DeleteFilter"},
		},
		{
			ID: ViewsPreview, Title: "Preview view", Version: VersionTag,
			Description:    "Compute served virtual time for an IP without sending NTP.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Preview"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/views/preview"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_views_preview"}},
			ServiceMethods: []string{"Preview"},
		},
		{
			ID: QueriesList, Title: "Query log", Version: VersionTag,
			Description:    "Last-N NTP query ring (authenticated). Reset wipes it.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "QueryList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/queries"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_queries_list"}},
			ServiceMethods: []string{"ListQueries"},
		},
		{
			ID: AuditList, Title: "Audit list", Version: VersionTag,
			Description:    "Query recent in-memory audit events.",
			RequiredScopes: []string{ScopeNTPAuditRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "AuditQuery"},
			OutputSchema:   &SchemaRef{Name: "AuditList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_audit_list"}, Resources: []string{"labntp://audit/recent"}},
			ServiceMethods: []string{"QueryAudit"},
		},
		{
			ID: AuditGet, Title: "Audit get", Version: VersionTag,
			Description:    "Get one audit event by ID.",
			RequiredScopes: []string{ScopeNTPAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditEvent"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit/{eventId}"}},
			MCP:            &MCPBinding{Tools: []string{"ntp_audit_get"}},
			ServiceMethods: []string{"GetAudit"},
		},
		{
			ID: MetricsGet, Title: "Metrics", Version: VersionTag,
			Description:    "OpenMetrics text. Served only when observability.metrics.publicPath is true.",
			RequiredScopes: []string{ScopeNTPRead}, Idempotent: true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/metrics"}},
		},
	}
}
