#!/usr/bin/env bash
# Freeze the characterization surface that the facade swap must not edit.
#
# Compares `git hash-object` of every tracked file in the set below, plus the
# set itself, with testdata/characterization.manifest. The hash is of the
# working tree file, so an unstaged edit fails. The manifest is not part of
# the frozen set.
#
#   internal/**/characterize_*_test.go
#   cmd/labntp/characterize_*_test.go
#   internal/control/mcp/probe_open_test.go
#   internal/testutil/difftranscript/**
#
# A deliberate PR-2 delta rewrites testdata/characterization.manifest in the
# same commit and says so. Regenerating the manifest is how that commit
# records the new bytes. A later edit that does not rewrite the manifest in
# that same commit fails this check.
#
#   scripts/check-characterization-frozen.sh          compare
#   scripts/check-characterization-frozen.sh --write  rewrite the manifest
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
export LC_ALL=C

manifest="testdata/characterization.manifest"
write=0
if [ "${1:-}" = "--write" ]; then
	write=1
elif [ -n "${1:-}" ]; then
	echo "usage: scripts/check-characterization-frozen.sh [--write]" >&2
	exit 2
fi

# git pathspec * does not match '/'. :(glob) does. Listing the difftranscript
# directory itself covers files that sit directly in it; ** alone can miss them.
files=$(git ls-files -- \
	':(glob)internal/**/characterize_*_test.go' \
	':(glob)cmd/labntp/characterize_*_test.go' \
	'internal/control/mcp/probe_open_test.go' \
	'internal/testutil/difftranscript')

if [ -z "$files" ]; then
	echo "check-characterization-frozen: no tracked characterization files" >&2
	exit 1
fi

current=$(mktemp)
trap 'rm -f "$current"' EXIT

while IFS= read -r f; do
	if [ -z "$f" ]; then
		continue
	fi
	if [ ! -f "$f" ]; then
		echo "check-characterization-frozen: $f is tracked but missing from the worktree" >&2
		exit 1
	fi
	hash=$(git hash-object -- "$f")
	printf '%s %s\n' "$hash" "$f"
done <<< "$files" | sort -k2 > "$current"

count=$(wc -l < "$current" | tr -d ' ')

if [ "$write" -eq 1 ]; then
	{
		echo "# Characterization freeze. git hash-object of the working tree."
		echo "# A deliberate PR-2 delta rewrites testdata/characterization.manifest in the same commit and says so."
		echo "# Do not edit this file by hand. Regenerate with scripts/check-characterization-frozen.sh --write."
		cat "$current"
	} > "$manifest"
	echo "check-characterization-frozen: wrote $manifest ($count files)"
	exit 0
fi

if [ ! -f "$manifest" ]; then
	echo "check-characterization-frozen: $manifest is missing" >&2
	exit 1
fi

recorded=$(mktemp)
trap 'rm -f "$current" "$recorded"' EXIT
grep -v -e '^#' -e '^$' "$manifest" | sort -k2 > "$recorded" || true

fail=0
while IFS= read -r line; do
	if [ -z "$line" ]; then
		continue
	fi
	path=${line#* }
	if ! grep -F -x -q -- "$line" "$current"; then
		if grep -F -q -- " $path" "$current"; then
			now=$(grep -F -- " $path" "$current" | head -n 1)
			echo "check-characterization-frozen: $path changed" >&2
			echo "  manifest $line" >&2
			echo "  working  $now" >&2
		else
			echo "check-characterization-frozen: $path is in the manifest but not tracked" >&2
		fi
		fail=1
	fi
done < "$recorded"

while IFS= read -r line; do
	if [ -z "$line" ]; then
		continue
	fi
	path=${line#* }
	if ! grep -F -q -- " $path" "$recorded"; then
		echo "check-characterization-frozen: $path is not in the manifest" >&2
		fail=1
	fi
done < "$current"

if [ "$fail" -ne 0 ]; then
	echo "check-characterization-frozen: failed" >&2
	echo "A deliberate PR-2 delta rewrites testdata/characterization.manifest in the same commit and says so." >&2
	exit 1
fi

echo "check-characterization-frozen: ok ($count files)"
